/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventarioapc.vistas;

import inventarioapc.controladores.Productos;
import inventarioapc.controladores.Ventanas;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolas soler & danny ochoa
 */
public class CajeroInicio extends javax.swing.JPanel {

    private String productoTemporal[];
    private DefaultTableModel modelo;
    public inventarioapc.controladores.Ventanas controladorNavegacion;
    public inventarioapc.controladores.Productos controladorProdcutos;
    public inventarioapc.vistas.CajeroFacturaDetalle detalleFac;
    /** Creates new form Cajero */
    public CajeroInicio(inventarioapc.vistas.CajeroFacturaDetalle detalleFac) {
        initComponents();
        asignarImagenes();
        this.detalleFac = detalleFac;
        productoTemporal = new String[7];
        modelo = new DefaultTableModel();
        
        modelo.addColumn("Indice");
        modelo.addColumn("Nombre");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        
        facturaPrev.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTable();
        cancelarFactura = new javax.swing.JButton();
        guardarFactura = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        busqueda = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        busquedaCod = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        facturaPrev = new javax.swing.JTable();
        subTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        codigoFac = new javax.swing.JTextField();
        precioFac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreFac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        agregarFactura = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cantidadFac = new javax.swing.JLabel();
        eliminarFactura = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 255, 236));

        jPanel1.setBackground(new java.awt.Color(149, 170, 184));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Marca", "Codigo", "Inventario"
            }
        ));
        productos.setRowHeight(40);
        productos.setRowMargin(2);
        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productos);

        jScrollPane1.setViewportView(jScrollPane2);

        cancelarFactura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cancelarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFacturaActionPerformed(evt);
            }
        });

        guardarFactura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        guardarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFacturaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(194, 214, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        busqueda.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("CODIGO:");

        busquedaCod.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(busquedaCod))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busqueda)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(busquedaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        facturaPrev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Precio"
            }
        ));
        facturaPrev.setRowHeight(40);
        facturaPrev.setRowMargin(2);
        jScrollPane3.setViewportView(facturaPrev);

        subTotal.setEditable(false);
        subTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        subTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subTotal.setText("0");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("SUB TOTAL: ");

        jPanel2.setBackground(new java.awt.Color(194, 214, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Codigo");

        codigoFac.setEditable(false);
        codigoFac.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        precioFac.setEditable(false);
        precioFac.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Precio");

        nombreFac.setEditable(false);
        nombreFac.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Nombre");

        agregarFactura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        agregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFacturaActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cantidadFac.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cantidadFac.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreFac, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigoFac, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioFac, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton5)
                        .addGap(66, 66, 66)
                        .addComponent(cantidadFac)
                        .addGap(59, 59, 59)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codigoFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombreFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(precioFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(cantidadFac))
                    .addComponent(agregarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        eliminarFactura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(guardarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(cancelarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eliminarFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFacturaActionPerformed
        //detalleFac.getTable().setModel(modelo);
        
        DefaultTableModel detalle = new DefaultTableModel();
        
        detalle.addColumn("Nombre");
        detalle.addColumn("Marca");
        detalle.addColumn("Codigo");
        detalle.addColumn("Precio");
        detalle.addColumn("Cantidad");
        String info[] = new String[5];
        int indice;
        
        for (int i = 0; i < facturaPrev.getRowCount(); i++) {
            indice = Integer.parseInt(facturaPrev.getValueAt(i, 0).toString());
            info[0] = productos.getValueAt(indice, 1).toString();
            info[1] = "--";
            info[2] = productos.getValueAt(indice, 0).toString();
            info[3] = facturaPrev.getValueAt(i, 3).toString();
            info[4] = facturaPrev.getValueAt(i, 2).toString();
            
            detalle.addRow(info);
        }
        
        detalleFac.getTotal().setText(subTotal.getText());
        detalleFac.getTable().setModel(detalle);
        controladorNavegacion.cambioVentana(2);
        limpiar();
    }//GEN-LAST:event_guardarFacturaActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseClicked
        int pos = productos.getSelectedRow();
                              
        codigoFac.setText(productos.getModel().getValueAt(pos, 0).toString());
        nombreFac.setText(productos.getModel().getValueAt(pos, 1).toString());
        precioFac.setText(productos.getModel().getValueAt(pos, 4).toString());
        
        productoTemporal[0] = codigoFac.getText();                                  //CODIGO
        productoTemporal[1] = nombreFac.getText();                                  //NOMBRE
        productoTemporal[2] = productos.getModel().getValueAt(pos, 2).toString();   //STOCKLOCAL
        productoTemporal[3] = productos.getModel().getValueAt(pos, 3).toString();   //STOCKBODEGA
        productoTemporal[4] = precioFac.getText();                                  //PRECIOVENTA
        productoTemporal[5] = productos.getModel().getValueAt(pos, 5).toString();   //PRECIOCOMPRA
        productoTemporal[6] = ""+00;                                                //CANTIDAD A LLEVAR
    }//GEN-LAST:event_productosMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(productoTemporal[6]!=null){
            int temp = Integer.parseInt(productoTemporal[6]);
            if(temp > 0){
                productoTemporal[6] = ""+(temp-1);
                if(temp-1 < 10){
                    cantidadFac.setText("0"+productoTemporal[6]);
                }else {
                    cantidadFac.setText(productoTemporal[6]);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(productoTemporal[6]!=null){
            int temp = Integer.parseInt(productoTemporal[6]);
            int stock = Integer.parseInt(productoTemporal[2]);
            if(temp < stock){
                productoTemporal[6] = ""+(temp+1);
                if(temp-1 < 10){
                    cantidadFac.setText("0"+productoTemporal[6]);
                }else {
                    cantidadFac.setText(productoTemporal[6]);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void agregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFacturaActionPerformed
        int i = productos.getSelectedRow();
        if(i>=0){
            int temporal = Integer.parseInt(productoTemporal[6]);
            DefaultTableModel modeloTemp = controladorProdcutos.getModelo();
            int stock = (Integer.parseInt(modeloTemp.getValueAt(i,2).toString())-temporal);
            if(temporal > 0 && stock >= 0){
                String info[] = new String[4];
                info[0] = ""+i;
                info[1] = productoTemporal[1];
                info[2] = productoTemporal[6];
                info[3] = productoTemporal[4];


                modeloTemp.setValueAt(stock, i, 2);
                info[3] = ""+ (Integer.parseInt(info[2]) * Integer.parseInt(info[3]));
                int subTotal = Integer.parseInt(this.subTotal.getText()) + Integer.parseInt(info[3]);
                modelo.addRow(info);
                this.subTotal.setText(""+subTotal);
            }else {
                if(stock < 0){
                    JOptionPane.showMessageDialog(null, "No hay suficientes productos en el stock local");
                }else{
                    JOptionPane.showMessageDialog(null, "Debe ingresar al menos un producto");
                }
            } 
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione el producto");
        }               
    }//GEN-LAST:event_agregarFacturaActionPerformed

    private void eliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFacturaActionPerformed
        int i = facturaPrev.getSelectedRow();
        DefaultTableModel temporal = controladorProdcutos.getModelo();
        
        int indice = Integer.parseInt(facturaPrev.getValueAt(i, 0).toString());
        int stock = Integer.parseInt(temporal.getValueAt(indice, 2).toString()) + Integer.parseInt(facturaPrev.getValueAt(i, 2).toString());
        temporal.setValueAt(stock, indice, 2);
        
        
        int subTotal = Integer.parseInt(this.subTotal.getText()) - (Integer.parseInt(facturaPrev.getValueAt(i, 2).toString()) * Integer.parseInt(facturaPrev.getValueAt(i, 3).toString()));
        this.subTotal.setText(""+subTotal);
        modelo.removeRow(i);
    }//GEN-LAST:event_eliminarFacturaActionPerformed

    private void cancelarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFacturaActionPerformed
        //limpiar();
    }//GEN-LAST:event_cancelarFacturaActionPerformed

    private void limpiar(){
        busqueda.setText("");
        busquedaCod.setText("");
        controladorProdcutos.actualizarTabla();
        
        int aux = facturaPrev.getRowCount();
        for (int i = 0; i < aux; i++) {
            facturaPrev.remove(0);
        }
        nombreFac.setText("");
        codigoFac.setText("");
        precioFac.setText("");
        cantidadFac.setText("00");
    }
    
    private void asignarImagenes(){
        agregarFactura.setIcon(setIcon("/images/aceptar.png", agregarFactura));
        eliminarFactura.setIcon(setIcon("/images/eliminar.png", cancelarFactura));
        guardarFactura.setIcon(setIcon("/images/save.png", guardarFactura));
        cancelarFactura.setIcon(setIcon("/images/stop.png", cancelarFactura));
    }
    
    private Icon setLogo(String url, JLabel label){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = label.getWidth();
        int alto = label.getHeight();
        
        ImageIcon imagen = new ImageIcon(icon.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        
        return imagen;
    }
    
    private Icon setIcon(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon imagen = new ImageIcon(icon.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        
        return imagen;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarFactura;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField busquedaCod;
    private javax.swing.JButton cancelarFactura;
    private javax.swing.JLabel cantidadFac;
    private javax.swing.JTextField codigoFac;
    private javax.swing.JButton eliminarFactura;
    private javax.swing.JTable facturaPrev;
    private javax.swing.JButton guardarFactura;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreFac;
    private javax.swing.JTextField precioFac;
    private javax.swing.JTable productos;
    private javax.swing.JTextField subTotal;
    // End of variables declaration//GEN-END:variables
    
    public Ventanas getControladorNavegacion() {
        return controladorNavegacion;
    }

    public void setControladorNavegacion(Ventanas controladorNavegacion) {
        this.controladorNavegacion = controladorNavegacion;
    }

    public JTable getTable() {
        return productos;
    }

    public Productos getControladorProdcutos() {
        return controladorProdcutos;
    }

    public void setControladorProdcutos(Productos controladorProdcutos) {
        this.controladorProdcutos = controladorProdcutos;
    }
    
}
